### ISSUE TITLE
Project cannot be cloned on Windows

### ISSUE THREAD

**Issue by Thiez** [rust-lang-nursery/rustc-perf#156]
The repository contains various files with names such as "site/tests/data/times/2017-04-30T13:38:12+00:00-06fb4d25642a3f223db1441972dd5962085cfba1-x86_64-unknown-linux-gnu.json"

Windows does not support "+" characters in filenames, and attempting to clone this project on a Windows machine will give a long list of errors saying:

    error: unable to create file site/tests/data/times/2017-01-13T07:24:53+00:00-b0c52c587fe9ba287053359fff5ed886b7edb27c-x86_64-unknown-linux-gnu.json (Invalid argument)

Since all of the offsets appear to be "+00:00", replacing all those by "Z" would be semantically equivalent, except that Windows would like it much better.

**Comment by pnkfelix** [comment]
It looks to me like there are two semi-related issues here: 
 * [ ] The `collector` code for running the compiler on the benchmark suite is using fragile filenames to hold its output.
 * [ ] Those fragile filenames are being checked into the repository. (I'm inferring that historically the files were in this repository, but now they have moved to https://github.com/rust-lang-nursery/rustc-timing )

The latter problem presumably could be fixed via a trivial renaming. But its not worth fixing the latter until the former is fixed.

(And of course, one might wonder whether this problem is worth investing time in fixing. Personally I'd prefer not to exclude potential contributors who are using Windows for development.)

**Comment by Mark-Simulacrum** [comment]
Fixing this shouldn't be too hard these days -- we mostly need to rename the files from DATE-sha-*.bincode to commit-sha-*.bincode which should be fairly easy to do. I'm going to go ahead and try that.

**Comment by Mark-Simulacrum** [comment]
This should now be fixed, as files are created without the time in their name.

**Comment by nnethercote** [comment]
FWIW, benchmarking is not possible on any platform other than Linux because it uses `perf`.

As for profiling:
- These will work on windows: `time-passes`, `eprintln`.
- These are Linux-only: `perf-record`, `oprofile`, `cachegrind`, `callgrind`, `exp-dhat`, `dhat`, `massif`.
