### ISSUE TITLE
Add `clap` to compile benchmarks

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#183]

**Comment by eddyb** [comment]
In my case, https://github.com/kbknapp/clap-rs/pull/1143 brings the build with my WIP MIR pass from 3h to 30s.
It just happened that RLS depends on v2.29.0 (https://github.com/kbknapp/clap-rs/commit/e962f2ceced8c04105ad12a4ca719daf2942667b), while the fix is in v2.29.1.
So if we want a stress test out of `clap`, we have to use v2.29.0. cc @kbknapp

**Comment by kbknapp** [comment]
Let me know if you need anything from my end, I'll keep an eye on this issue in case.

**Comment by Mark-Simulacrum** [comment]
Added clap at e962f2ceced8c04105ad12a4ca719daf2942667b, collection has begun.
