### ISSUE TITLE
Using a better encoding for graph data

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang-nursery/rustc-perf#224]
Currently, the graph data is encoded in a naive fashion with JSON. This is very inefficient, as the string duplication causes it to process, encode, transfer and decode slowly.

An alternative would be using a table-like structure. We first encode row and column names, then we encode all the numbers in a 2D array. This removes most of the duplication, and makes it process on the client faster. In the absence of data, we just replace it with a null.

Additionally, MessagePack can be used to reduce the overhead encoding floats. This can cut off more than half of the uncompressed data.

**Comment by Mark-Simulacrum** [comment]
We've since moved to storing some information out of band and such, the current download size is around ~700 KB for the front page data. I do think this can be reduced further if we invested time, but I'm going to close this issue as that amount seems much more reasonable than the 10+ MB we were downloading before.
