### ISSUE TITLE
Dashboard missing new versions

### ISSUE THREAD

**Issue by BO41** [rust-lang-nursery/rustc-perf#427]
The [dashboard](https://perf.rust-lang.org/dashboard.html) is showing 1.34 as latest version with beta and master.
But now version 1.36 is stable (+ beta 1.37 + master nightly).

Please update to the new versions :)

**Comment by Mark-Simulacrum** [comment]
Updated! Thanks for the reminder; I kept forgetting to do this.

**Comment by BO41** [comment]
@Mark-Simulacrum ping :wink: 

Is there a way for you to automate this? would be nice

**Comment by Mark-Simulacrum** [comment]
Yeah I'll reopen this and track automating it here. Should be not _hard_ persay, just a bit of work...

**Comment by Mark-Simulacrum** [comment]
okay I've moved us closer to having it automated with some changes to the run script that's on the collection server, and we should hopefully have data for 1.37 in several hours. If that all goes well I'll also add 1.38 and beta data sometime in the next week (I don't want to do it all in one go since that'll be a long process and we will hurt perf queue)

**Comment by Mark-Simulacrum** [comment]
Okay I should hopefully be better about this from now on, though it's not entirely automated, it's almost so. For now sufficiently so :)

Closing this.
