### ISSUE TITLE
detailed view: "% Total Time" alt-text is wrong or confusing

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang-nursery/rustc-perf#528]
Hovering over the `% Total Time` value says `% of wall-time stat` which is not what we want (because the sum of the numbers below is the total CPU-time). 

So the question is: Is the alt-text wrong or is the alt-text right and the underlying computation wrong?

**Comment by Mark-Simulacrum** [comment]
This was intended as a "feature" rather than a "bug." i.e., it is not a sum but in fact shows the percentage of CPU time accounted for by self-profile.

However, I think it might be more confusing than it's worth, and we should just drop this. I'm not sure how useful it is -- it seems like it's about ~100% most of the time

**Comment by michaelwoerister** [comment]
My main concern is that it says "wall-time" instead of "cpu-time". However, that is not always 100% might be confusing too.

**Comment by Mark-Simulacrum** [comment]
We can rephrase that -- I agree that's confusing. We doo have the clarifying sentence that just says "this is why we use cpu time"
