### ISSUE TITLE
"could not find cargo home dir" when running collector

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang-nursery/rustc-perf#542]
Trying to run the collector on my (Linux) machine fails with "failed to obtain pkgid [...]" caused by cargo failing on "could not find cargo home dir".
After investigation, it appears that cargo tries to find its `$HOME/.cargo` (or equivalent) directory to store some state in, and therefore needs a way to find the user's home directory. However the `$HOME` environment variable is being unset here: https://github.com/rust-lang-nursery/rustc-perf/blob/fadd80097c0d1a31f64f069b4a11f9b9dba5bf75/collector/src/bin/rustc-perf-collector/execute.rs#L161-L165
In common configurations, this doesn't error because cargo falls back to using `getpwuid_r` to determine the home directory (as mentioned [here](https://docs.rs/home/0.5.1/home/fn.home_dir.html#unix)). In my configuration however my user is not in the `/etc/passwd` file (this is a managed workstation), so this fails.
A simple fix is to add the `$HOME` variable manually to the command environment, like what is currently done for `$SHELL` and `$PATH`.

**Comment by Mark-Simulacrum** [comment]
Sounds fine to add it in, I'd be happy to accept a PR doing so.

(Over time, I've felt that maybe that env_clear is actually more trouble than it's worth, but we do somewhat want it still I think due to clearing cargo-specific env variables, e.g. CARGO_INCREMENTAL -- but maybe that's not worth the hassle).
