### ISSUE TITLE
some indication on the web page when crates don't build

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/rustc-perf#68]
There seem to be a number of issues about error-handling, but none of them with much description. Right now the set of benchmarks that appear on `perf.rust-lang.org` is much smaller than the full set that appears in <https://github.com/rust-lang-nursery/rustc-benchmarks>. I *think* the reason is that some of those benchmarks fail to build -- but there is no indication of this! Very easy to lose sight of a benchmark this way.

**Comment by Mark-Simulacrum** [comment]
I see a couple approaches to this problem:
 - Scan the last commit's raw logs for failures and display this (new page? summary page?)
  - with a programmatic version of `git diff-tree --no-commit-id --name-only -r HEAD | grep 'raw' | grep -- '--0' | xargs grep failed`)
 - Compare last two runs and if there's a lack of crate then report that. More faulty, but doesn't require additional scanning/running of commands on file read.

**Comment by Mark-Simulacrum** [comment]
Okay, talked with nrc on IRC, agreed on this:
 - Restructure the summary table to show every crate
   - "-" in place of percents when we don't have data; and something like an "error" if it stops building; linked to the raw log in the github repo

Will require updates to [`process.py`](https://github.com/rust-lang-nursery/rustc-timing-scripts/blob/master/process.py) so that it creates files of a format similar to `{ "error": ["raw/path-to-log", ...] }`.

**Comment by Mark-Simulacrum** [comment]
Closing due to #88; see the PR description/commit for reasoning as to a potentially better fix has not been implemented.
