### ISSUE TITLE
Factor out title and summary HTML into one place

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang-nursery/rustc-perf#85]
The overall decision is that moving towards generating shared HTML in `shared.js` and inserting it into the relevant page is the best approach.

---

Currently, the menu and the settings HTML is mostly duplicated from page to page. This makes editing it difficult; I propose that we move to generating the HTML from a template. This can either be done at-runtime in Rust, at-runtime in JS, or statically.

If we decide on at-runtime, I think doing it in JS makes more sense. Something like [React](https://facebook.github.io/react/) or [Vue.js](https://vuejs.org/) may be worth looking into, though they may be overly complicated.

@dikaiosune: Can you provide any recommendations based on your work with the [dashboard](http://rusty-dash.com)?

cc @nrc

**Comment by dikaiosune** [comment]
The dashboard uses Ember. Which had a bit of yak shaving but is now pretty easy to add things to. Using Handlebars on the dashboard makes life easy, although type checking would certainly be nice :smile:. I'd be open to hosting perf.rlo's display pages out of the dashboard's Ember app, although that'd be problematic with the existing perf.rlo address, and I'm sure there'd be other issues there. I think the principle issue with contributing to the dashboard is the test debt which I need to fix.

I'm not super up to date on how mature templating libraries are in Rust. I was looking at https://github.com/Keats/tera which looks cool, but I haven't tried it yet. I believe there are also multiple Handlebars implementations in Rust.

You could probably just get away with jQuery + Handlebars for rendering, unless you need more sophisticated navigation or UI complexity. Since IIRC the perf data is updated infrequently, ISTM that a static generator would be easy to set up on whatever cron job or scheduled task currently adds data to the site? Granted having runtime generation means one fewer moving piece to break when updating the data...

My opinion is that given the bajillion ways to render HTML, it's largely a matter of preference. I used Ember because the dashboard has a very open-ended project scope, and needs to be easily modified as different metrics need to be surfaced over the life of the project. Also, I had little experience with a proper JS framework, Ember seemed to require less yak shaving than React (picking libraries etc.) and wasn't in the middle of a second-system transition like Angular is, and the Ember community has some overlap with the Rust community (at least in part due to wycats's close involvement with both).

**Comment by nrc** [comment]
I would avoid Ember for this - it is very heavyweight and mostly not necessary for this kind of work (to be clear, it is a great framework - I had a good experience using it for rustaceans.org, I just think it is a bit too much for here).

I think handlebars is probably a good fit and is all client-side which makes hosting easier. React could work well too - I don't think there is too much extra libs to use etc if you only want to make a component for the menu bar. However, you then download a non-trivial lib with every page :-(

Could we just create the menu, etc. in JS and keep it in shared.js? It doesn't seem to me like we need a more sophisticated approach than that here?

**Comment by Mark-Simulacrum** [comment]
I think that at least for now, we can go with generating any shared components in JS, with a potential for long term moving to Ember, React, etc. if deemed necessary. Will update the original comment to reflect that.

Re-triaging as P-medium since the duplication I noted isn't highly critical to fix.

---

Thanks for such a detailed response, @dikaiosune! Helped clear things up about rusty-dash for sure, will be useful if we ever decide to integrate perf.rlo with it, and helped clear things up with regards to Ember.

**Comment by Mark-Simulacrum** [comment]
Reducing priority since status quo isn't really hurting us. If (and when) we decide to add more pages this can be increased in priority/fixed.

**Comment by Mark-Simulacrum** [comment]
I think some basic templating system would make sense here -- maybe handlebars or even just replacing `$MENU$` with some string would be fine.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this as a templating system seems like overkill and we can just copy the headers for now - we don't add/remove pages that often.
